using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Server.Models;

namespace ExpenseTracker.Server.Data;

public class ExpenseTrackerDbContext : DbContext
{
    public ExpenseTrackerDbContext(DbContextOptions<ExpenseTrackerDbContext> options)
        : base(options)
    {
    }

    public DbSet<Expense> Expenses { get; set; }
    public DbSet<Category> Categories { get; set; }
    public DbSet<Budget> Budgets { get; set; }
    public DbSet<RecurringExpense> RecurringExpenses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Expense configuration
        modelBuilder.Entity<Expense>(entity =>
        {
            // PostgreSQL stores unquoted identifiers as lowercase
            // If created via Supabase UI, table is likely "expenses"
            entity.ToTable("expenses");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Amount).HasPrecision(18, 2);
            entity.Property(e => e.Description).HasMaxLength(200).IsRequired();
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.HasIndex(e => e.Date);
            entity.HasIndex(e => e.CategoryId);
            entity.HasIndex(e => e.CreatedAt);
            
            entity.HasOne(e => e.Category)
                .WithMany(c => c.Expenses)
                .HasForeignKey(e => e.CategoryId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Category configuration
        modelBuilder.Entity<Category>(entity =>
        {
            // PostgreSQL stores unquoted identifiers as lowercase
            // If created via Supabase UI, table is likely "categories"
            entity.ToTable("categories");
            entity.HasKey(c => c.Id);
            
            // Map column names to match Supabase table (all lowercase)
            entity.Property(c => c.Id)
                .HasColumnName("id")
                .ValueGeneratedOnAdd(); // Auto-increment for bigint
            entity.Property(c => c.CreatedAt)
                .HasColumnName("created_at")
                .IsRequired()
                .HasDefaultValueSql("CURRENT_TIMESTAMP"); // Default to current timestamp
            entity.Property(c => c.Name)
                .HasColumnName("name")
                .HasMaxLength(50)
                .IsRequired();
            entity.Property(c => c.Icon)
                .HasColumnName("icon")
                .HasMaxLength(50);
            entity.Property(c => c.Color)
                .HasColumnName("color")
                .HasMaxLength(7);
            entity.Property(c => c.IsDefault)
                .HasColumnName("\"isDefault\""); // Use quoted identifier to preserve camelCase
            entity.Property(c => c.ParentCategoryId)
                .HasColumnName("\"parentCategoryId\""); // Use quoted identifier to preserve camelCase
            
            entity.HasIndex(c => c.Name).IsUnique();
            
            entity.HasOne(c => c.ParentCategory)
                .WithMany(c => c.SubCategories)
                .HasForeignKey(c => c.ParentCategoryId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Budget configuration
        modelBuilder.Entity<Budget>(entity =>
        {
            // PostgreSQL stores unquoted identifiers as lowercase
            entity.ToTable("budgets");
            entity.HasKey(b => b.Id);
            entity.Property(b => b.Amount).HasPrecision(18, 2);
            
            entity.HasOne(b => b.Category)
                .WithMany(c => c.Budgets)
                .HasForeignKey(b => b.CategoryId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // RecurringExpense configuration
        modelBuilder.Entity<RecurringExpense>(entity =>
        {
            // PostgreSQL stores unquoted identifiers as lowercase
            entity.ToTable("recurringexpenses");
            entity.HasKey(r => r.Id);
            entity.Property(r => r.Amount).HasPrecision(18, 2);
            entity.Property(r => r.Description).HasMaxLength(200).IsRequired();
            
            entity.HasOne(r => r.Category)
                .WithMany()
                .HasForeignKey(r => r.CategoryId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Seed default categories
        SeedDefaultCategories(modelBuilder);
    }

    private void SeedDefaultCategories(ModelBuilder modelBuilder)
    {
        // Note: If using bigint IDs, these will be auto-generated by the database
        // Seed data should be inserted via SQL or application code, not HasData
        // HasData with bigint requires explicit ID values that don't conflict with auto-increment
    }
}

